version: '3.7'

services:
    dbtest:
        image: registry.2le.net/2le/[PROJECT]:dbtest

    symfony:
        build: .
        working_dir: /var/www/html
        ports:
          - "8000:80"
        volumes:
            - ./:/var/www/html/
        environment:
            - "COMPOSER_MEMORY_LIMIT=-1"
        depends_on:
            - dbtest

    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - dbtest:db
        ports:
            - "9000:80"
        depends_on:
            - dbtest
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
